# Generated by Django 5.1.7 on 2025-03-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_address_address_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='balance',
            field=models.BigIntegerField(default=0),
        ),
    ]
