# Generated by Django 5.1.7 on 2025-03-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_address_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='balance',
            field=models.CharField(max_length=200),
        ),
    ]
