# Generated by Django 5.1.7 on 2025-03-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_address_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='balance',
        ),
        migrations.AddField(
            model_name='address',
            name='etherscan_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
